name: Build AyuGram Windows

on:
  workflow_dispatch:  # Запуск вручную
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare dependencies
        shell: cmd
        run: |
          cd Telegram\build\prepare
          call win.bat

      - name: Configure
        shell: cmd
        run: |
          cd Telegram
          configure.bat x64 -D TDESKTOP_API_ID=2040 -D TDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627

      - name: Build Release
        shell: cmd
        run: |
          cd out
          cmake --build . --config Release --target Telegram -- /maxcpucount

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-Release
          path: out/Release/Telegram.exe
